### ISSUE TITLE
stardrop windows not loading mods

### ISSUE THREAD

**Issue by herp2derp** [Floogen/Stardrop#13] opened 2021-12-31 18:06 UTC
i did all the settings correctly like the smapi path, mod folder path.
select all the mods i want active and started the game with the button in the top right
when the game started up it didn't load any mod. sorry for any bad english
[log.txt](https://github.com/Floogen/Stardrop/files/7796825/log.txt)
[smapi log.txt](https://github.com/Floogen/Stardrop/files/7796826/smapi.log.txt)
![stardrop screenshot](https://user-images.githubusercontent.com/96922385/147835106-af2e8777-0967-4e6e-b7d5-87abe7901f53.PNG)
s

**Comment by Floogen** [comment] 2021-12-31 21:32
This likely is resolved with v1.0.0-beta.11.

If you are still having problems, I'll need another log file from you as I've added additional debugging details.

**Comment by herp2derp** [comment] 2021-12-31 22:11
still have the problem here you have the log file, also put in je smapi log just in case. (happy New Year) and don't work yourself to hard.
[log.txt](https://github.com/Floogen/Stardrop/files/7797133/log.txt)
[smapi log.txt](https://github.com/Floogen/Stardrop/files/7797134/smapi.log.txt)
i see that someone else also made a issue tread of "Smapi doesn't load mods above a certain amount through Stardrop" maybe this is the problem (this is the problem i have that it work with 49 mods but when i go to 50 it breaks.)

**Comment by Floogen** [comment] 2022-01-01 19:44
Duplicate of #14

**Comment by Floogen** [comment] 2022-01-01 21:15
v1.0.0-beta.12 should hopefully resolve that issue.

Thank you for reporting this.

**Closed as completed by Floogen** 2022-01-01 21:15 UTC
Labels: bug, duplicate

**Comment by herp2derp** [comment] 2022-01-01 22:03
v1.0.0-beta.12 indeed fixed this problem
