### ISSUE TITLE
Can't start program in windows

### ISSUE THREAD

**Issue by GeekPorridge** [Floogen/Stardrop#185] opened 2024-04-14 11:53 UTC
When I open the program in Windows, it can start, but nothing happens. The program cannot be opened at all. Can you help me fix it? I really like this software.

**Comment by Kombwucha** [comment] 2024-04-14 17:05
Same here, Stardrop application is running but it can't be opened at all. 

![image](https://github.com/Floogen/Stardrop/assets/127721078/7bf618bf-77b5-45cd-b39a-9c4c5578e005)

**Comment by Floogen** [comment] 2024-04-14 17:39
Please follow the [instructions for reporting issues](https://floogen.gitbook.io/stardrop/resources/reporting-issues) with Stardrop. I am unable to help without a log file.

**Comment by agriffin5675** [comment] 2024-04-14 18:30
Having the same issue. First time using this site so hopefully my logs are uploading correctly.

[smapi log](https://smapi.io/log/a2e22731d33a4d0db3a9ca34cf797491)
[log.txt](https://github.com/Floogen/Stardrop/files/14971717/log.txt)

**Comment by Floogen** [comment] 2024-04-14 19:15
> Having the same issue. First time using this site so hopefully my logs are uploading correctly.
> 
> [smapi log](https://smapi.io/log/a2e22731d33a4d0db3a9ca34cf797491) [log.txt](https://github.com/Floogen/Stardrop/files/14971717/log.txt)

Could you see if [v1.1.1-beta.1](https://github.com/Floogen/Stardrop/releases/tag/v1.1.1-beta.1) resolves this issue? If not, I will need another log file.

**Comment by Kombwucha** [comment] 2024-04-14 19:24
[log.txt](https://github.com/Floogen/Stardrop/files/14971841/log.txt)
Unfortunately, it still doesn't work even with the beta file.

**Comment by Floogen** [comment] 2024-04-14 20:30
I am unable to replicate the issue, so this is proving a little challenging to pinpoint the cause. Please bear with me as we work through this!

This is still unlikely to fix it, but could you test [v1.1.1-beta.8](https://github.com/Floogen/Stardrop/releases/tag/v1.1.1-beta.8) and return another log file? Thank you!

**Comment by Floogen** [comment] 2024-04-14 23:04
This has been resolved with [v1.1.1](https://github.com/Floogen/Stardrop/releases/tag/v1.1.1).

**Closed as completed by Floogen** 2024-04-14 23:04 UTC
