### ISSUE TITLE
Mac Version:The problem of unable to load mod remains unresolved

### ISSUE THREAD

**Issue by lilinonearth** [Floogen/Stardrop#15] opened 2022-01-01 02:04 UTC
The new version is better than the previous version, but the pre mod of large mod cannot be loaded.
[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/7797292/SMAPI-latest.txt)
[log.txt](https://github.com/Floogen/Stardrop/files/7797293/log.txt)

**Comment by Floogen** [comment] 2022-01-01 19:44
Duplicate of #14

**Closed as completed** 2022-01-01 21:06 UTC
Labels: bug, duplicate
