### ISSUE TITLE
Stardrop unable to open even with latest version?

### ISSUE THREAD

**Issue by Kombwucha** [Floogen/Stardrop#189] opened 2024-04-15 00:15 UTC
Stardrop still refuses to show up even if the application is evidently running and open. Experimentation of using the v1.1 beta and the latest v1.1 stardrop application produces the same results. Unsure if I should uninstall all stardrop applications currently and then use the latest. Please advise.
![image](https://github.com/Floogen/Stardrop/assets/127721078/d05fcca2-4daf-4468-9a57-7aa7c3453e4b)

[log.txt](https://github.com/Floogen/Stardrop/files/14972680/log.txt)

**Comment by Floogen** [comment] 2024-04-15 00:32
Duplicate of #188.

**Closed as completed by Floogen** 2024-04-15 00:32 UTC
